### PR TITLE
Add support for datadog.

### PR DESCRIPTION
**Pull request by EnTeQuAk**
This is part of tackling mozilla/addons#1636

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
I'll check the test-failures and get this cleaned up in the next few days.

**Comment by EnTeQuAk** [comment]
@michael-k or @xordoquy any chance you have some time to look at this?

**Comment by michael-k** [comment]
Sorry, I don't have the commit bit for this repo.  Other than that, the change looks fine to me.

**Comment by xordoquy** [comment]
I somehow heard that wasn't used any longer, is it still ?

**Comment by EnTeQuAk** [comment]
> I somehow heard that wasn't used any longer, is it still ?

What are you referring to? django-statsd? At least we at addons.mozilla.org are still using it at the moment.

**Comment by xordoquy** [comment]
sorry, my question was about datalog. Will try to get a release out tomorrow.

**Comment by EnTeQuAk** [comment]
Well, this is about [data**d**og](datadoghq.com) and yeh, it's used quite a lot in the wild :)

>  Will try to get a release out tomorrow.

That's awesome, thanks a lot!

**Comment by EnTeQuAk** [comment]
@xordoquy hey, do you have the time to push a new release of this to pypi some time?

**Pull request merged**
